Notifier
codex-team/js-notifier pull request #1
Opened 2017-06-27 00:11 UTC by gohabereg

2017-06-27 09:25 UTC, khaydarov requested changes

2017-06-27 09:25 UTC, khaydarov commented on webpack.config.js
> +              presets: [__dirname + '/node_modules/babel-preset-es2015']
можно просто presets: ['es2015'] - вроде пофиксили пути уже.

2017-06-27 11:19 UTC, neSpecc commented
где-то можно посмотреть внешний вид?

2017-06-27 14:22 UTC, talyguryn commented
@neSpecc запусти это в консоли на каком-нибудь сайте

```js
var z = function () {
    notifier.show({message: 'Just a notify message', time: 20000});
    notifier.show({message: 'Do you agree?', type: 'confirm'});
    notifier.show({message: 'Enter your name', type: 'prompt'});
    notifier.show({message: 'Welcome to error', style: 'error', time: 20000});
    notifier.show({message: 'You are the winner', style: 'success', time: 20000});
};

var x = document.createElement('SCRIPT');
x.src = "https://rawgit.com/codex-team/js-notifier/initial/notifier.js";
x.onload = z;
document.body.appendChild(x);

var y = document.createElement('LINK');
y.rel = "stylesheet";
y.href = "https://rawgit.com/codex-team/js-notifier/initial/notifier.css";
document.body.appendChild(y);
```

2017-06-27 22:49 UTC, khaydarov approved these changes

2017-06-28 10:16 UTC, neSpecc commented on README.md
> +- `style` — just add `'cdx-notifies__notification--' + style` class. We have some default styles: `success` and `error`
может переделаем на `cdx-notify--` ?  чтобы уведомление было блоком. Лучше выглядеть будет

2017-06-28 17:42 UTC, talyguryn requested changes

2017-06-28 17:42 UTC, talyguryn commented on README.md
> +  message: 'Sory, server is busy now',
sorry

2017-06-28 17:56 UTC, neSpecc approved these changes

2017-06-28 17:56 UTC, neSpecc approved these changes

2017-06-28 17:58 UTC, talyguryn approved these changes

2017-06-28 18:01 UTC, merged